name: Sync Twinfield WSDL

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync-wsdl:
    name: Sync Twinfield WSDL files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download WSDL files
        run: |
          mkdir -p wsdl
          curl --fail "https://accounting.twinfield.com/webservices/BankBookService.svc?wsdl" --output wsdl/BankBookService.svc.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/BankStatementService.svc?wsdl" --output wsdl/BankStatementService.svc.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/CashBookService.svc?wsdl" --output wsdl/CashBookService.svc.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/declarations.asmx?wsdl" --output wsdl/declarations.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/DocumentService.svc?wsdl" --output wsdl/DocumentService.svc.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/ebankstatements.asmx?wsdl" --output wsdl/ebankstatements.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/finder.asmx?wsdl" --output wsdl/finder.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/hierarchies.asmx?wsdl" --output wsdl/hierarchies.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/matching.asmx?wsdl" --output wsdl/matching.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/payandcollect.asmx?wsdl" --output wsdl/payandcollect.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/PeriodService.svc?wsdl" --output wsdl/PeriodService.svc.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/processxml.asmx?wsdl" --output wsdl/processxml.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/sbr.asmx?wsdl" --output wsdl/sbr.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/session.asmx?wsdl" --output wsdl/session.asmx.wsdl
          curl --fail "https://accounting.twinfield.com/webservices/versions.asmx?wsdl" --output wsdl/versions.asmx.wsdl

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if files changed
        run: |
          git add wsdl/
          if ! git diff --cached --quiet; then
            git commit -m "Update Twinfield WSDL files"
            git push
          else
            echo "No changes to commit"
          fi
